[color_scheme]

[color_scheme.palette]
    bright_divider = "255,151,151,151"
    mid_text = "255,187,187,187"
    bright_highlight = "255,50,50,50"
    search_bar_background = "255,44,50,59"
    light_background = "255,44,50,59"
    bright_text = "255,237,191,105"
    # Side divider that separates sections and options
    dark_divider = "255,36,42,50"
    # Option cards themselves
    dark_highlight = "255,38,40,45"
    dark_text = "255,119,119,121"
    accent = "255,144,201,102"
    transparent = "0,0,0,0"
    modal_background = "255,44,50,59"
    highlight = "255,33,34,38"
    outline = "255,48,48,49"
    # Borders for option cards
    divider = "255,36,42,50"
    background = "255,44,50,59"
    success = "255,1,165,82"
    scroll_bar = "255,45,45,45"
    dark_background = "255,44,50,59"
    warning = "255,239,83,80"
    disabled = "255,80,80,80"
